# frozen_string_literal: true

source 'https://rubygems.org'
gem 'cssminify'
gem 'jekyll-gfm-admonitions', path: '..', group: :jekyll_plugins
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll'
gem 'jekyll-remote-theme'
gem 'octicons'
